name: Senggol CIA

on:
 push:
  branches: [ master ]
 #pull_request:

jobs:
 build-image-and-deploy-to-docker-hub:
  runs-on: ubuntu-latest
  steps:
   - name: Checkout
     uses: actions/checkout@v2
   - name: Login to Docker hub 
     uses: docker login-action@v1
     with:
      username: ${{ secrets.DOCKERHUB_USERNAME }}
      password: ${{ secrets.DOCKERHUB_TOKEN }}
   - name: Setup Docker Buildx
     uses: docker/setup-buildx-action@v1
   - name: Build and push senggol backend
     uses: docker/build-push-action@v2
     with:
      context: ./senggol
      push: true
      tags: arslan-caerleon/senggol-backend:latest
   - name: Build and push senggol frontend
     uses: docker/build-push-action@v2
     with:
      context: ./senggol-frontend
      push: true
      tags: arslan-caerleon/senggol-frontend:latest              
